services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ../:/app
    environment:
      - MYSQL_DB=alsjounral
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
  db:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 5230:5230
    environment:
      - MYSQL_DATABASE=alsjounral
      - MYSQL_ROOT_PASSWORD=root
volumes:
  mysql:
